import Link from "next/link";
import { cookies } from "next/headers";
import { SettingOutlined } from "@ant-design/icons";
import { getWord } from "@/words";
import { jwtDecode, JwtHeader } from "jwt-decode";

export default function DefaultLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Gets username from either a uuid cookie generated by server or grabs it from keycloak
  // const username = cookies().get("user")
  //   ? getWord(cookies().get("user")?.value as string)
  //   : cookies().get("KEYCLOAK_IDENTITY")
  //     ? cookies().get("KEYCLOAK_IDENTITY")?.value
  //     : undefined;
  // if (cookies().get("KEYCLOAK_IDENTITY")) {
  //   console.log(
  //     JSON.stringify(
  //       jwtDecode<JwtHeader>(
  //         cookies().get("KEYCLOAK_IDENTITY")?.value as string
  //       ).alg
  //     )
  //   );
  // }
  return (
    <>
      <nav className="m-4 flex w-screen items-center font-mono *:text-sm min-[340px]:*:text-xl sm:*:text-3xl">
        <Link
          href="/"
          className="transform transition hover:scale-105 hover:text-gray-400"
        >
          Music server
        </Link>
        <div className="absolute right-0 mr-4 flex">
          <span className="!text-lg mr-4">
            {cookies().get("username")
              ? "Logged in as " + cookies().get("username")?.value
              : cookies().get("KEYCLOAK_REMEMBER_ME")
                ? cookies().get("KEYCLOAK_REMEMBER_ME")?.value
                : "Not logged in"}
          </span>
          <Link
            href="/admin"
            className="transform transition hover:scale-105 hover:text-gray-400"
          >
            <SettingOutlined className="flex aspect-square h-full justify-center" />
          </Link>
        </div>
      </nav>
      {children}
    </>
  );
}
